clear all;
close all;
clc;

%%

% label = {'cheer up', ...
%          'toss paper', ...
%          'lie on sofa',...
%          'walk', ...
%          'stand up', ...
%          'sit down',...
%          'sit down',...
%          'sit down',...
%          'sit down',...
%          'sit down',...
%          'sit down'};
     
     
label= {'depo. flo.',...
        'elbo. kne.',...
        'grab high',...
        'hop leg.',...
        'jog',...
        'kick forw.',...
        'lie flo.',...
        'rot. arm.',...
        'sneak',...
        'squat',...
        'thr. bas.'};
     
load('cmat.mat');
%%
cmat = cmat;


n_class = length(cmat);
for i = 1:n_class
   cmat(i,:) = cmat(i,:) ./ sum(cmat(i,:)); 
end

drawConfusionMatrix(cmat, label);



